name: DEV

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull project
        uses: actions/checkout@v3

      - name: Send project to remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .
          remote: /var/www/quwi
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}

      - name: Rebuild and Restart containers
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /var/www/quwi/deployment
            docker-compose up --build -d
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
